SET SERVEROUTPUT ON

CREATE OR REPLACE FUNCTION MAYOR(N1 NUMBER, N2 NUMBER, N3 NUMBER)
RETURN NUMBER IS
    V1 NUMBER := N1;
    V2 NUMBER := N2;
    V3 NUMBER := N3;
    MAYOR NUMBER := 0;

BEGIN
    IF N1 >= N2 AND N1 >= N3 THEN
        MAX_VAL := N1;
    ELSIF N2 >= N1 AND N2 >= N3 THEN
        MAX_VAL := N2;
    ELSE
        MAX_VAL := N3;
    END IF;
    
    RETURN MAYOR;
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Error general');
END;
/

SELECT MAYOR(2,5,3) FROM DUAL;