SET SERVEROUTPUT ON

CREATE OR REPLACE PROCEDURE ACTUALIZAR_FECHA_ALTA(NOMBRE DEPARTAMENTO.NOMBRE%TYPE) IS
    V_NOMBRE DEPARTAMENTO.NOMBRE%TYPE := NOMBRE;
    V_FECHA DATOSPERSONALES.FECHA_ALTA%TYPE;
    V_MENSAJE VARCHAR2(2) := 'OK';
BEGIN
    SELECT MIN(FECHA_ALTA) INTO V_FECHA
    FROM DEPARTAMENTO D, EMPLEADOS E, DATOSPERSONALES DP
    WHERE D.NOMBRE = V_NOMBRE
    AND D.ID_DEPARTAMENTO = E.ID_DEPARTAMENTO
    AND DP.CLAVE_EMPLEADO = E.ID_EMPLEADO;

    UPDATE DATOSPERSONALES
    SET FECHA_ALTA = SYSDATE
    WHERE FECHA_ALTA = V_FECHA;

    DBMS_OUTPUT.PUT_LINE(V_MENSAJE);
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Error general');
END;
/

CALL ACTUALIZAR_FECHA_ALTA('Personal');

SELECT DP.*
FROM DEPARTAMENTO D, EMPLEADOS E, DATOSPERSONALES DP
WHERE D.NOMBRE = 'Personal'
AND D.ID_DEPARTAMENTO = E.ID_DEPARTAMENTO
AND DP.CLAVE_EMPLEADO = E.ID_EMPLEADO
ORDER BY DP.FECHA_ALTA DESC;