SET SERVEROUTPUT ON

CREATE OR REPLACE PROCEDURE INVERTIR(CAD VARCHAR2) IS
    CADENA VARCHAR2(200) := CAD;
    INVERTIDA VARCHAR2(200) := '';
    CAR VARCHAR2(1) := '';
BEGIN
    FOR V IN REVERSE 1..LENGTH(CADENA) LOOP
        CAR := SUBSTR(CADENA, V, 1);
        INVERTIDA := INVERTIDA || CAR;
    END LOOP;
    
    DBMS_OUTPUT.PUT_LINE(INVERTIDA);
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Error general');
END;
/

CALL INVERTIR('Hola Mundo.');