SET SERVEROUTPUT ON

-- WHILE - FETCH
CREATE OR REPLACE PROCEDURE P_PERSONAL IS
    NOMBRE EMPLEADOS.NOMBRE%TYPE;
    FECHA_ALTA DATOSPERSONALES.FECHA_ALTA%TYPE;

    CURSOR NOMBRES IS
        SELECT NOMBRE
        FROM EMPLEADOS;
    CURSOR FECHAS IS
        SELECT FECHA_ALTA
        FROM DATOSPERSONALES;
BEGIN
    OPEN NOMBRES;
    OPEN FECHAS;

    FETCH NOMBRES INTO NOMBRE;
        WHILE NOMBRES%FOUND LOOP
            DBMS_OUTPUT.PUT_LINE(NOMBRE);
            FETCH NOMBRES INTO NOMBRE;
        END LOOP;
    
    FETCH FECHAS INTO FECHA_ALTA;
        WHILE FECHAS%FOUND LOOP
            DBMS_OUTPUT.PUT_LINE(FECHA_ALTA);
            FETCH FECHAS INTO FECHA_ALTA;
        END LOOP;

    CLOSE NOMBRES;
    CLOSE FECHAS;
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Error general');
END;
/

CALL P_PERSONAL();



-- LOOP - FETCH
CREATE OR REPLACE PROCEDURE P_PERSONAL IS
    NOMBRE EMPLEADOS.NOMBRE%TYPE;
    FECHA_ALTA DATOSPERSONALES.FECHA_ALTA%TYPE;

    CURSOR NOMBRES IS
        SELECT NOMBRE
        FROM EMPLEADOS;
    CURSOR FECHAS IS
        SELECT FECHA_ALTA
        FROM DATOSPERSONALES;
BEGIN
    OPEN NOMBRES;
    OPEN FECHAS;

    LOOP
        FETCH NOMBRES INTO NOMBRE;
        EXIT WHEN NOMBRES%NOTFOUND;
        DBMS_OUTPUT.PUT_LINE(NOMBRE);
    END LOOP;
    
    LOOP
        FETCH FECHAS INTO FECHA_ALTA;
        EXIT WHEN FECHAS%NOTFOUND;
        DBMS_OUTPUT.PUT_LINE(FECHA_ALTA);
    END LOOP;

    CLOSE NOMBRES;
    CLOSE FECHAS;
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Error general');
END;
/

CALL P_PERSONAL();



-- FOR
CREATE OR REPLACE PROCEDURE P_PERSONAL IS
    NOMBRE EMPLEADOS.NOMBRE%TYPE;
    FECHA_ALTA DATOSPERSONALES.FECHA_ALTA%TYPE;

    CURSOR NOMBRES IS
        SELECT NOMBRE
        FROM EMPLEADOS;
    CURSOR FECHAS IS
        SELECT FECHA_ALTA
        FROM DATOSPERSONALES;
BEGIN
    OPEN NOMBRES;
    OPEN FECHAS;

    LOOP
        FETCH NOMBRES INTO NOMBRE;
        EXIT WHEN NOMBRES%NOTFOUND;
        DBMS_OUTPUT.PUT_LINE(NOMBRE);
    END LOOP;
    
    LOOP
        FETCH FECHAS INTO FECHA_ALTA;
        EXIT WHEN FECHAS%NOTFOUND;
        DBMS_OUTPUT.PUT_LINE(FECHA_ALTA);
    END LOOP;
    
    CLOSE NOMBRES;
    CLOSE FECHAS;
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Error general');
END;
/

CALL P_PERSONAL();