SET SERVEROUTPUT ON

-- 1
CREATE OR REPLACE PROCEDURE DNI_EMP(CLAVE_EMPLEADO DATOSPERSONALES.CLAVE_EMPLEADO%TYPE) IS
    V_CLAVE_EMPLEADO DATOSPERSONALES.CLAVE_EMPLEADO%TYPE := CLAVE_EMPLEADO;
    V_DNI DATOSPERSONALES.DNI%TYPE;
BEGIN
    SELECT DNI INTO V_DNI
    FROM DATOSPERSONALES
    WHERE V_CLAVE_EMPLEADO = CLAVE_EMPLEADO;

    DBMS_OUTPUT.PUT_LINE('DNI del empleado: ' || V_DNI);
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Error general');
END;
/

CALL DNI_EMP('EMP01');

-- 2
CREATE OR REPLACE FUNCTION EMPLEADOS_PERSONAL
RETURN NUMBER IS
    V_NUM NUMBER;
BEGIN
    SELECT COUNT(*) INTO V_NUM
    FROM DEPARTAMENTO D, EMPLEADOS E, DATOSPERSONALES DP
    WHERE D.NOMBRE = 'Personal'
    AND D.ID_DEPARTAMENTO = E.ID_DEPARTAMENTO
    AND E.ID_EMPLEADO = DP.CLAVE_EMPLEADO;

    RETURN V_NUM;
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Error general');
END;
/

SELECT EMPLEADOS_PERSONAL() FROM DUAL;

-- 3
CREATE OR REPLACE FUNCTION EMPLEADOS_PERSONAL2(NOMBRE DEPARTAMENTO.NOMBRE%TYPE)
RETURN NUMBER IS
    V_NOMBRE DEPARTAMENTO.NOMBRE%TYPE := NOMBRE;
    V_NUM NUMBER;
BEGIN
    SELECT COUNT(*) INTO V_NUM
    FROM DEPARTAMENTO D, EMPLEADOS E, DATOSPERSONALES DP
    WHERE D.NOMBRE = V_NOMBRE
    AND D.ID_DEPARTAMENTO = E.ID_DEPARTAMENTO
    AND E.ID_EMPLEADO = DP.CLAVE_EMPLEADO;

    RETURN V_NUM;
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Error general');
END;
/

SELECT EMPLEADOS_PERSONAL2('Personal') FROM DUAL;