SET SERVEROUTPUT ON

CREATE OR REPLACE PROCEDURE CONDUCTOR IS
    FECHA DATE;
BEGIN
    SELECT * INTO V_CONDUCTOR
    FROM CONDUCTOR;

    SELECT FECHA_VIAJE INTO FECHA
    FROM CONDUCTOR
    WHERE FECHA_VIAJE = (
        SELECT MIN(NUM_EMPLEADO)
        FROM CONDUCTOR
    );

    DBMS_OUTPUT.PUT_LINE('La fecha de viaje es: ' || FECHA);
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Error general');
END;
/

CALL CONDUCTOR();