SET SERVEROUTPUT ON

CREATE OR REPLACE FUNCTION PAR_IMPAR(NUM NUMBER)
RETURN VARCHAR2 IS
    V_NUM NUMBER := NUM;
    V_BOOL VARCHAR2(5) := '';
BEGIN
    IF MOD(NUM, 2) = 0 THEN
        V_BOOL := 'TRUE';
    ELSE
        V_BOOL := 'FALSE';
    END IF;

    RETURN V_BOOL;
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Error general');
END;
/

SELECT PAR_IMPAR(2) FROM DUAL;
SELECT PAR_IMPAR(5) FROM DUAL;