SET SERVEROUTPUT ON

CREATE OR REPLACE FUNCTION AREA_CIRCULO(RADIO NUMBER)
RETURN NUMBER IS
    V_RAD NUMBER := RADIO;
    V_AREA NUMBER := 0;
BEGIN
    V_AREA := 3.14 * V_RAD * V_RAD;

    RETURN V_AREA;
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Error general');
END;
/

SELECT AREA_CIRCULO(5) FROM DUAL;